ProjetoFolha/Controllers/CadastroFuncionarioController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProjetoFolha.Data;
using ProjetoFolha.Filters;
using ProjetoFolha.Models;
using ProjetoFolha.Repositorio;
using System.Security.Cryptography.X509Certificates;
using System.Text;

namespace ProjetoFolha.Controllers
{
    [UsuarioVerificacaoPerfil]
    public class CadastroFuncionarioController : Controller
    {
        private readonly ICadastroFuncionarioRepositorio _cadastroFuncionarioRepositorio;

        public CadastroFuncionarioController(
            ICadastroFuncionarioRepositorio cadastroFuncionarioRepositorio
        )
        {
            _cadastroFuncionarioRepositorio = cadastroFuncionarioRepositorio;
        }

        //CadastroFuncionarioModel teste = new CadastroFuncionarioModel();
        public IActionResult Index()
        {
            List<CadastroFuncionarioModel> Funcionarios =
                _cadastroFuncionarioRepositorio.BuscarTodos();
            return View(Funcionarios);
        }

        public IActionResult CadastroFuncionario()
        {
            return View();
        }

        public IActionResult EditarFuncionario(int id)
        {
            CadastroFuncionarioModel funcionario = _cadastroFuncionarioRepositorio.ListarPorId(id);
            return View(funcionario);
        }
        
        public IActionResult InativarFuncionario(int id)
        {
            CadastroFuncionarioModel funcionario = _cadastroFuncionarioRepositorio.ListarPorId(id);
            return View(funcionario);
        }

        public IActionResult DeletarCadastro(int id)
        {
            try
            {
                bool apagado = _cadastroFuncionarioRepositorio.Apagar(id);

                if (apagado) TempData["MensagemSucesso"] = "Contato apagado com sucesso!"; else TempData["MensagemErro"] = "Ops, não conseguimos cadastrar seu contato, tente novamante!";
                return RedirectToAction("Index");
            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Ops, não conseguimos apagar seu contato, tente novamante, detalhe do erro: {erro.Message}";
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public IActionResult CadastroFuncionario(CadastroFuncionarioModel cadastro)
        {
            //Valida os campos do formulario
            if (
                string.IsNullOrEmpty(cadastro.nome)
                || string.IsNullOrEmpty(cadastro.senha)
                || string.IsNullOrEmpty(cadastro.email)
            )
            {
                ModelState.AddModelError(
                    "",
                    "Por favor, preencha todos os campos antes de cadastrar."
                );
                return View(cadastro); // Retorna a view com os dados preenchidos pelo usuário para que ele possa corrigir
            }
            Console.WriteLine("Cadastro" + cadastro);
            string senha = cadastro.senha;
            string encodedStr = Convert.ToBase64String(Encoding.UTF8.GetBytes(senha)); // Criptografia da senha
            cadastro.senha = encodedStr;
            //string inputStr = Encoding.UTF8.GetString(Convert.FromBase64String(encodedStr));// discriptografia da senha
            string sexo = cadastro.sexoSelecionado;
            _cadastroFuncionarioRepositorio.Adicionar(cadastro);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult EditarFuncionario(CadastroFuncionarioModel cadastro)
        {
            if (
                string.IsNullOrEmpty(cadastro.nome)
                || string.IsNullOrEmpty(cadastro.senha)
                || string.IsNullOrEmpty(cadastro.email)
            )
            {
                ModelState.AddModelError(
                    "",
                    "Por favor, preencha todos os campos antes de cadastrar."
                );
                return View(cadastro); // Retorna a view com os dados preenchidos pelo usuário para que ele possa corrigir
            }
            Console.WriteLine("Cadastro" + cadastro);
            string senha = cadastro.senha;
            string encodedStr = Convert.ToBase64String(Encoding.UTF8.GetBytes(senha)); // Criptografia da senha
            cadastro.senha = encodedStr;
            //string inputStr = Encoding.UTF8.GetString(Convert.FromBase64String(encodedStr));// discriptografia da senha
            string sexo = cadastro.sexoSelecionado;
            _cadastroFuncionarioRepositorio.Atualizar(cadastro);
            return RedirectToAction("Index");
        }

        public IActionResult hth()
        {
            List<SetorModel> setor =
                _cadastroFuncionarioRepositorio.BuscarSetores();
            return View(setor);
        } 
    }
}

ProjetoFolha/Controllers/SetorController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using ProjetoFolha.Models;
using ProjetoFolha.Repositorio;

namespace ProjetoFolha.Controllers
{
    public class SetorController : Controller
    {

        private readonly ISetorRepositorio _setorRepositorio;

        public SetorController(ISetorRepositorio setorRepositorio)   
        {
            _setorRepositorio = setorRepositorio;
        }

        public IActionResult CadastrarSetor()
        {
            return View();
        }

        /*public IActionResult CadastrarSetor()
        {
            List<SetorModel> setores =
                _setorRepositorio.BuscarTodos();
            return View(setores);
        }*/

        [HttpPost]
        public IActionResult CadastroSetor(SetorModel setor)
        {
            
            try
            {
                
                
                
                if (setor.Descricao != null)
                {   
                    
                    _setorRepositorio.AdicionarSetor(setor);
                    TempData["MensagemSucesso"] = $"Setor cadastrado.";
                    return RedirectToAction("CadastrarSetor");
                    
                }
                

                return RedirectToAction("CadastrarSetor");

            }
            catch (Exception erro)
            {

                TempData["MensagemErro"] = $"Ops, não conseguimos cadastrar seu setor, tente novamante, detalhe do erro: {erro.Message}";
                return RedirectToAction("CadastrarSetor");
            }

        }

    }
}

ProjetoFolha/Views/Setor/CadastrarSetor.cshtml
@model SetorModel
@{
    ViewData["Title"] = "Cadastro de Setor";
    Layout = "_LayoutMain";
}

<main id="main" class="main">
    <div class="text-center">
        <div class="pagetitle">
            <h1>Cadastro de Setor</h1>
        </div>
    </div>
    
    @if (TempData["MensagemSucesso"] != null)
    {
        <div id="sucesso" class="alert alert-success" role="alert">
            @TempData["MensagemSucesso"]
            <script>
                setTimeout(function () {
                    document.getElementById("sucesso").style.display = "none";
                }, 3000);
                function hide() {
                    document.getElementById("sucesso").style.display = "none";
                }
            </script>
        </div>
    }
    @if (TempData["MensagemErro"] != null)
    {
        <div class="alert alert-danger" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert" data-bs-dismiss="alert" aria-label="Close">X</button>
            @TempData["MensagemErro"]
            <script>
                setTimeout(function () {
                    document.getElementById("sucesso").style.display = "none";
                }, 3000);
                function hide() {
                    document.getElementById("sucesso").style.display = "none";
                }
            </script>
        </div>
    }
    @Html.ValidationSummary()
    <section class="section">
        <div class="row">
            <div class="texte-center">

                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Informações do Setor</h5>
                        <form asp-controller="SetorController" asp-action="CadastroSetor" method="post">
                            <div class="row mb-3">
                                <label for="inputText" class="col-sm-2 col-form-label">Descrição do Setor</label>
                                   <div class="col-sm-10">
                                      <input type="text" asp-for="Descricao" class="form-control">
                                   </div>
                                </div>
                                <p>
                                <p>
                            <div class="row mb-3">
                                <div class="d-flex justify-content-between">
                                    <a role="button" class="btn btn-secondary" asp-controller="CadastroFuncionario" asp-action="Index"> Voltar</a>
                                        <button type="submit" class="btn btn-success" asp-controller="Setor" asp-action="CadastroSetor">Cadastrar</button>
                                </div>
                            </div>
                        </form>

                    </div>
                </div>

            </div>
        </div>
    </section>

</main>